### PR TITLE
fix: get rootProject values for build.gradle

### PR DESCRIPTION
**Pull request by alarm109**
## Description

Gets the values for build.gradle options from rootProject.

## Motivation and Context

If build.gradle options are different from rootProject it may not build.

## How Has This Been Tested?
Installed in project and ran build command.

### Checklist

- This is a breaking change:
  - [ ] Yes
  - [x] No
- Will this release a new version:
  - [x] Yes, minor
  - [ ] No

### CODE REVIEW

**Review by lukebars — COMMENTED** [review]
Sweet! Do you think we might be able to check for minimum version? e.g. If user's project has really old SDK version, we could throw an error or fallback to a newer version. Just a thought

**Comment by alarm109** [comment]
I think if the user uses a really old sdk version he will get a build error anyway. 😅
I checked other rn packages and all of them do the same thing.

**Review by lukebars — APPROVED** [review]

**Comment by lukebars** [comment]
Could we also use project's RN version? Or are we already doing that? That would help in such cases as in recent RN fallout with accidental alpha publish breaking the old RN version builds.

**Comment by alarm109** [comment]
We are already doing that. Native modules take RN version from node_modules for all packages. And fitness tracker has peerDependancies RN in package.json, so it uses project's version.

**Pull request merged**
